#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const { chromium } = require('playwright');

function arg(name, fallback = '') {
  const idx = process.argv.indexOf(name);
  return idx >= 0 && process.argv[idx + 1] ? process.argv[idx + 1] : fallback;
}

const interactive = process.argv.includes('--interactive-login');
const outFile = arg('--out', path.resolve(__dirname, '..', 'config', 'instagram-cookies.txt'));
const stateFile = arg('--state', path.resolve(__dirname, '..', 'config', 'instagram-storage-state.json'));
const timeoutSec = Number(arg('--timeout-sec', '180'));

function ensureDir(filePath) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
}

function toNetscapeCookieLine(c) {
  const domain = c.domain.startsWith('.') ? c.domain : `.${c.domain}`;
  const includeSubdomains = 'TRUE';
  const cookiePath = c.path || '/';
  const secure = c.secure ? 'TRUE' : 'FALSE';
  const expiry = Number.isFinite(c.expires) && c.expires > 0 ? Math.floor(c.expires) : 0;
  return [domain, includeSubdomains, cookiePath, secure, String(expiry), c.name, c.value].join('\t');
}

(async () => {
  ensureDir(outFile);
  ensureDir(stateFile);

  const hasState = fs.existsSync(stateFile);
  const browser = await chromium.launch({ headless: !interactive });
  const context = await browser.newContext(hasState ? { storageState: stateFile } : {});
  const page = await context.newPage();

  await page.goto('https://www.instagram.com/', { waitUntil: 'domcontentloaded' });

  if (interactive) {
    console.log('Interactive mode: completa login/2FA en la ventana del navegador.');
    const end = Date.now() + timeoutSec * 1000;
    while (Date.now() < end) {
      const u = page.url();
      if (!u.includes('/accounts/login')) break;
      await page.waitForTimeout(1000);
    }
  }

  const current = page.url();
  if (current.includes('/accounts/login')) {
    await browser.close();
    console.error('ERROR: No hay sesión activa de Instagram. Ejecuta con --interactive-login.');
    process.exit(2);
  }

  await context.storageState({ path: stateFile });
  const cookies = await context.cookies('https://www.instagram.com/');
  const igCookies = cookies.filter(c => c.domain.includes('instagram.com'));

  const lines = [
    '# Netscape HTTP Cookie File',
    '# Generated by Playwright automation for yt-dlp',
    ...igCookies.map(toNetscapeCookieLine)
  ];
  fs.writeFileSync(outFile, lines.join('\n') + '\n', 'utf8');

  await browser.close();
  console.log(outFile);
})();